language: node_js
node_js:
- "6.11.0"
install: npm install
services:
- postgresql
before_script:
- psql -c 'drop database if exists food_direct;' -U postgres
- psql -c 'create database food_direct;' -U postgres
- npm run migrate
script: npm test
after_success: npm run coverage
